#!/bin/bash
if [ "$#" -eq 0 ]; then
  printf "Missing verb. Usage: kibana verb path. Example: kibana PUT pages\n";
  exit
fi

verb=$1
shift

if [ "$#" -eq 0 ]; then
  printf "Missing path. Usage: kibana verb path. Example: kibana PUT pages\n";
  exit
fi

path=$1
shift

if [ "$#" -eq 0 ]; then
  curl -s -N http://localhost:9200$path -X $verb -H 'Content-Type: application/json'
else
  curl -s -N http://localhost:9200$path -X $verb -H 'Content-Type: application/json' -d "$1"
fi
