# Fixtures shared among texts
euclid = {
    'raw_text': "To draw a straight line from any point to any point.\nTo produce a finite straight line continuously in a straight line.\nTo describe a circle with any center and radius.\nThat all right angles equal one another.\nThat, if a straight line falling on two straight lines makes the interior angles on the same side less than two right angles, the two straight lines, if produced indefinitely, meet on that side on which are the angles less than the two right angles.",
    'keyword_list': ['angles', 'interior angles', 'straight line', 'straight line falling', 'angles equal', 'straight lines', 'straight lines makes', 'finite straight line'],
    'keyword_list_nltk': ['right angles equal one another', 'side', 'interior angles', 'two straight lines makes', 'two straight lines', 'straight line', 'straight line falling', 'side less', 'angles less', 'two right angles', 'finite straight line'],
    'anchor_page_ids': [18973446, 9417, 946975]
}

wave_fields = {
    'raw_text': "Consider a nonparametric representation of acoustic wave fields that consists of observing the sound pressure along a straight line or a smooth contour L defined in space. The observed data contains implicit information of the surrounding acoustic scene, both in terms of spatial arrangement of the sources and their respective temporal evolution. We show that such data can be effectively analyzed and processed in what we call the space-time-frequency representation space, consisting of a Gabor representation across the spatio-temporal manifold defined by the spatial axis L and the temporal axis t. In the presence of a source, the spectral patterns generated at L have a characteristic triangular shape that changes according to certain parameters, such as the source distance and direction, the number of sources, the concavity of L, and the analysis window size. Yet, in general, the wave fronts can be expressed as a function of elementary directional components-most notably, plane waves and far-field components. Furthermore, we address the problem of processing the wave field in discrete space and time, i.e., sampled along L and t, where a Gabor representation implies that the wave fronts are processed in a block-wise fashion. The key challenge is how to chose and customize a spatio-temporal filter bank such that it exploits the physical properties of the wave field while satisfying strict requirements such as perfect reconstruction, critical sampling, and computational efficiency. We discuss the architecture of such filter banks, and demonstrate their applicability in the context of real applications, such as spatial filtering, deconvolution, and wave field coding.",
    'keyword_list': ['analysis window size', 'key challenge', 'plane waves', 'wave field coding', 'spatio-temporal filter bank', 'characteristic triangular shape', 'sound pressure', 'space', 'source', 'spatial axis', 'spatial filtering', 'physical properties', 'space-time-frequency representation space', 'gabor representation', 'computational efficiency', 'straight line', 'acoustic wave fields', 'nonparametric representation', 'far-field components', 'perfect reconstruction', 'spatial arrangement', 'wave fronts', 'gabor representation implies', 'spatio-temporal manifold', 'source distance', 'filter banks', 'discrete space', 'block-wise fashion', 'elementary directional components-', 'time', 'surrounding acoustic scene', 'data', 'critical sampling', 'temporal axis', 'real applications', 'smooth contour', 'respective temporal evolution', 'spectral patterns', 'satisfying strict requirements', 'wave field', 'implicit information'],
    'keyword_list_nltk': ['analysis window size', 'key challenge', 'plane waves', 'wave field coding', 'characteristic triangular shape', 'temporal filter bank', 'field components', 'space', 'source', 'wise fashion', 'temporal manifold', 'spatial filtering', 'physical properties', 'elementary directional components', 'computational efficiency', 'straight line', 'acoustic wave fields', 'nonparametric representation', 'perfect reconstruction', 'data contains implicit information', 'spatial arrangement', 'wave fronts', 'gabor representation implies', 'spatial axis l', 'source distance', 'filter banks', 'gabor representation across', 'discrete space', 'e . , l', 'certain parameters', 'l', 'surrounding acoustic scene', 'data', 'critical sampling', 'temporal axis', 'sound pressure along', 'real applications', 'frequency representation space', 'respective temporal evolution', 'spectral patterns', 'satisfying strict requirements', 'wave field', 'changes according', 'smooth contour l'],
    'anchor_page_ids': [8525, 1198]
}

schreier = {
    'raw_text': "We are interested in various aspects of spectral rigidity of Cayley and Schreier graphs of finitely generated groups. For each pair of integers, we consider an uncountable family of groups of automorphisms of the rooted d-regular tree, which provide examples of the following interesting phenomena. We get an uncountable family of non-quasi-isometric Cayley graphs with the same Laplacian spectrum, a union of two intervals, which we compute explicitly. Some of the groups provide examples where the spectrum of the Cayley graph is connected for one generating set and has a gap for another. We exhibit infinite Schreier graphs of these groups with the spectrum a Cantor set of Lebesgue measure zero union a countable set of isolated points accumulating on it. The Kesten spectral measures of the Laplacian on these Schreier graphs are discrete and concentrated on the isolated points. We construct, moreover, a complete system of eigenfunctions that are strongly localized.",
    'keyword_list': ['compute', 'isolated points accumulating', 'countable set', 'exhibit infinite schreier graphs', 'spectrum', 'laplacian', 'd-regular tree', 'complete system', 'groups provide examples', 'provide examples', 'spectral rigidity', 'cantor set', 'laplacian spectrum', 'cayley graph', 'non-quasi-isometric cayley graphs', 'schreier graphs', 'isolated points', 'lebesgue measure', 'interesting phenomena', 'groups', 'uncountable family', 'kesten spectral measures', 'cayley', 'generating set'],
    'keyword_list_nltk': ['compute', 'isolated points accumulating', 'countable set', 'exhibit infinite schreier graphs', 'spectrum', 'laplacian', 'one generating set', 'complete system', 'groups provide examples', 'regular tree', 'following interesting phenomena', 'provide examples', 'various aspects', 'spectral rigidity', 'cantor set', 'laplacian spectrum', 'cayley graph', 'isometric cayley graphs', 'schreier graphs', 'lebesgue measure zero union', 'isolated points', 'two intervals', 'groups', 'uncountable family', 'union', 'kesten spectral measures', 'cayley'],
    'anchor_page_ids': [206137, 19873]
}

fixtures = [euclid, wave_fields, schreier]
