#---------------------------#
# Your server configuration #
#---------------------------#

[database]
host: ...
# If running on localhost, use host: host.docker.internal
port: ...
user: ...
password: ...

[elasticsearch]
host: ...
# If running on localhost, use host: host.docker.internal
port: ...
username: ...
password: ...
cafile: /app/certs/[ES_CERT_FILENAME from .env].crt
# The path /app/certs is internal on docker, not your local path
concept_detection_index: concepts_detection_2025-06-26

[auth]
schema: graphai_auth
secret_key: ...
# Generate secret key with "openssl rand -hex 32"

[google]
api_key: <api_key>

#------------------------------------#
# Do not change anything bellow here #
#------------------------------------#

[celery]
broker_url: amqp://guest:guest@rabbitmq:5672//
result_backend: redis://redis:6379/1

[cache]
root: /var/graphai/storage
schema: graphai_cache

[fingerprint]
text: 1.0
image: 1.0
audio: 1.0
video: 1.0

[whisper]
model_type: small
model_path: /opt/models/whisper

[huggingface]
model_path: /opt/models/huggingface

[fasttext]
path: /opt/models/fasttext
dim: 30

[cleanup]
interval: 30

[preload]
video: yes
text: yes
ontology: no

[ratelimiting]
limit: unlimited
custom_limits:

[logging]
path: /var/graphai/logs
server_name: graphai_local%
