name: "Clone repo"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  clone-repo:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Create config files
        run: |
          cd main
          mkdir config
          cd config
          
          echo "[DB]" >> db.ini
          echo "host: ${{ vars.db_host }}" >> db.ini
          echo "port: ${{ vars.db_port }}" >> db.ini
          echo "user: ${{ vars.db_user }}" >> db.ini
          echo "password: ${{ secrets.db_password }}" >> db.ini
          
          echo "[ES]" >> es.ini
          echo "host: ${{ vars.es_host }}" >> es.ini
          echo "port: ${{ vars.es_port }}" >> es.ini
          echo "username: ${{ vars.es_username }}" >> es.ini
          echo "password: ${{ secrets.es_password }}" >> es.ini
          echo "cafile: ${{ vars.es_cafile }}" >> es.ini
          
          echo "[CELERY]" >> celery.ini
          echo "broker_url: ${{ vars.celery_broker_url }}" >> celery.ini
          echo "result_backend: ${{ vars.celery_result_backend }}" >> celery.ini
          
          echo "[WHISPER]" >> models.ini
          echo "model_type: ${{ vars.whisper_model_type }}" >> models.ini
          echo "" >> models.ini
          echo "[GOOGLE]" >> models.ini
          echo "api_key: ${{ secrets.google_api_key }}" >> models.ini
          echo "" >> models.ini
          echo "[CHATGPT]" >> models.ini
          echo "api_key: ${{ secrets.openai_api_key }}" >> models.ini
          
          
          echo "[CACHE]" >> cache.ini
          echo "root: ${{ vars.cache_root }}" >> cache.ini
          echo "schema: ${{ vars.cache_schema }}" >> cache.ini

      - name: Install python package in editable mode along with dependencies from the correct virtual environment
        run: |
          cd main
          source /data/venvs/test_venv/bin/activate
          pip install -e .
          python -c "import spacy; spacy.cli.download('en_core_web_lg') if 'en_core_web_lg' not in spacy.util.get_installed_models() else None"
          python -c "import spacy; spacy.cli.download('fr_core_news_md') if 'fr_core_news_md' not in spacy.util.get_installed_models() else None"
          python -c "import whisper; whisper.load_model('${{ vars.whisper_model_type }}');"
          python -c "from transformers import AutoModelForSeq2SeqLM; AutoModelForSeq2SeqLM.from_pretrained('Helsinki-NLP/opus-mt-en-fr')"
          python -c "from transformers import AutoModelForSeq2SeqLM; AutoModelForSeq2SeqLM.from_pretrained('Helsinki-NLP/opus-mt-fr-en')"

      - name: Run linter
        run: |
          cd main
          source /data/venvs/test_venv/bin/activate
          flake8 --ignore=E501,W503 graphai
