name: "Deploy API"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy-api:
    runs-on: self-hosted

    steps:
      - name: Copy repo
        run: |
          rm -r /home/ubuntu/graphai-test
          cp -r main /home/ubuntu/graphai-test

      - name: Deploy API and associated services
        run: |
          systemctl --user stop celery-flower
          systemctl --user stop api-test
          systemctl --user stop celery-low-prio
          systemctl --user stop celery-mid-prio
          systemctl --user stop celery-caching
          systemctl --user stop celery-high-prio
          systemctl --user stop celery-beat
          ################
          systemctl --user start celery-beat
          systemctl --user start celery-high-prio
          systemctl --user start celery-caching
          systemctl --user start celery-mid-prio
          systemctl --user start celery-low-prio
          systemctl --user start api-test
          systemctl --user start celery-flower
