name: "Deploy API"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy-api:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          path: /home/ubuntu/graphai-test

      - name: Copy config folder
        run: |
          cp -r main/config /home/ubuntu/graphai-test

      - name: Deploy API
        run: systemctl --user restart api-test
