name: "Deploy API"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy-api:
    runs-on: self-hosted

    steps:
      - name: Copy repo
        run: |
          rm -r /home/ubuntu/graphai-test
          cp -r main /home/ubuntu/graphai-test

      - name: Deploy API
        run: systemctl --user restart api-test
