name: "Deploy API"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy-api:
    runs-on: self-hosted

    steps:
      - name: Deploy API
        run: |
          cd main/graphai/api
          # ./deploy.sh -p ${{ vars.api_test_port }}
