name: "Run tests, build docs and deploy API"

on:
  workflow_dispatch:

  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "**"

jobs:
  clone-repo:
    uses: ./.github/workflows/clone-repo.yml
    secrets: inherit

  run-tests:
    needs: [clone-repo]
    uses: ./.github/workflows/run-tests.yml

  copy-repo:
    if: github.event_name == 'push'
    needs: [run-tests]
    uses: ./.github/workflows/copy-repo.yml

  build-docs:
    if: github.event_name == 'push'
    needs: [copy-repo]
    uses: ./.github/workflows/build-docs.yml

  update-gh-pages:
    if: github.event_name == 'push'
    needs: [build-docs]
    uses: ./.github/workflows/update-gh-pages.yml

  deploy-api:
    if: github.event_name == 'push'
    needs: [copy-repo]
    uses: ./.github/workflows/deploy-api.yml
