name: "Run tests"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Run tests
        run: |
          cd /home/ubuntu/graphai-test/tests
          source /data/venvs/test_venv/bin/activate
          pytest
