name: "Update gh-pages"

on:
  workflow_dispatch:

  workflow_call:

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifact of the html output
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: main/docs/build/html/

      - name: Checkout gh-pages branch in another folder
        uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages

      - name: Commit documentation changes
        run: |
          rm -r gh-pages/*
          cp -r main/docs/build/html/* gh-pages/
          cd  gh-pages/
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # The command below will fail if no changes were present, so we ignore that.
          git commit -m "doc from ${{ github.ref }} @ ${{ github.sha }}" || true

      - name: Push documentation changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
